SELECT SYSPROCESSES.SPID,
  DM_EXEC_REQUESTS.BLOCKING_SESSION_ID,
  SYSPROCESSES.STATUS,
  SYSPROCESSES.HOSTNAME,
  SYSPROCESSES.LOGINAME,
  SYSPROCESSES.CPU,
  DM_EXEC_REQUESTS.CPU_TIME,
  DM_EXEC_REQUESTS.START_TIME,
  DM_EXEC_REQUESTS.TOTAL_ELAPSED_TIME,
  DM_EXEC_REQUESTS.COMMAND,
  SYSPROCESSES.PROGRAM_NAME,
  HDNL.TEXT
FROM SYS.DM_EXEC_REQUESTS,
  MASTER.DBO.SYSPROCESSES
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SYSPROCESSES.SQL_HANDLE) AS HDNL
WHERE SYSPROCESSES.STATUS NOT IN ('sleeping', 'background') 
  AND DM_EXEC_REQUESTS.SESSION_ID = SYSPROCESSES.SPID