SELECT TOP 1 WITH TIES CRITERIO, LOC_DEST, COMPANY_DEST
FROM TIME_CUTTING.db_edw.TRANSF_CUSTOMER_CARE
ORDER BY ROW_NUMBER() OVER (PARTITION BY [CRITERIO] ORDER BY NEWID())
-- CRITERIO  LOC_DEST	COMPANY_DEST
-- A         542        500
-- B         1577       397
-- C         3153       496
