USE EDW;
SELECT SYS_DF.NAME,
  SIZE / 128.0 AS USER_SPACE_IN_MB,
  SYS_DF.SIZE / 128.0 - CAST(FILEPROPERTY(SYS_DF.NAME, 'SPACEUSED') AS INT) / 128.0 AS AVAILABLE_SPACE_IN_MB
FROM SYS.DATABASE_FILES AS SYS_DF