SELECT DM_EXEC_SESSIONS.HOST_NAME,
  DM_EXEC_SESSIONS.LOGIN_NAME,
  DM_EXEC_QUERY_MEMORY_GRANTS.SESSION_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.REQUEST_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.SCHEDULER_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.DOP,
  DM_EXEC_QUERY_MEMORY_GRANTS.REQUEST_TIME,
  DM_EXEC_QUERY_MEMORY_GRANTS.GRANT_TIME,
  DM_EXEC_QUERY_MEMORY_GRANTS.REQUESTED_MEMORY_KB,
  DM_EXEC_QUERY_MEMORY_GRANTS.GRANTED_MEMORY_KB,
  DM_EXEC_QUERY_MEMORY_GRANTS.REQUIRED_MEMORY_KB,
  DM_EXEC_QUERY_MEMORY_GRANTS.QUERY_COST,
  DM_EXEC_QUERY_MEMORY_GRANTS.TIMEOUT_SEC,
  DM_EXEC_QUERY_MEMORY_GRANTS.RESOURCE_SEMAPHORE_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.QUEUE_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.WAIT_ORDER,
  DM_EXEC_QUERY_MEMORY_GRANTS.IS_NEXT_CANDIDATE,
  DM_EXEC_QUERY_MEMORY_GRANTS.WAIT_TIME_MS,
  DM_EXEC_QUERY_MEMORY_GRANTS.PLAN_HANDLE,
  DM_EXEC_QUERY_MEMORY_GRANTS.SQL_HANDLE,
  DM_EXEC_QUERY_MEMORY_GRANTS.GROUP_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.POOL_ID,
  DM_EXEC_QUERY_MEMORY_GRANTS.IS_SMALL,
  DM_EXEC_QUERY_MEMORY_GRANTS.IDEAL_MEMORY_KB
FROM SYS.DM_EXEC_QUERY_MEMORY_GRANTS
INNER JOIN SYS.DM_EXEC_SESSIONS
  ON DM_EXEC_QUERY_MEMORY_GRANTS.SESSION_ID = DM_EXEC_SESSIONS.SESSION_ID
ORDER BY QUERY_COST DESC