SELECT CASE DATEPART(DW, GETDATE())
  WHEN 1 THEN 'SUNDAY'
  WHEN 2 THEN 'MONDAY'
  WHEN 3 THEN 'TUESDAY'
  WHEN 4 THEN 'WEDNESDAY'
  WHEN 5 THEN 'THURSDAY'
  WHEN 6 THEN 'FRIDAY'
  ELSE 'SATURDAY'
END
-- MONDAY