-- MUST CONFIGURE AUDIT FIRST (audit working)
-- ACTION_ID: https://cprovolt.wordpress.com/2013/08/02/sql-server-audit-action_id-list/
SELECT EVENT_TIME,
  SESSION_SERVER_PRINCIPAL_NAME AS USERNAME,
  SERVER_INSTANCE_NAME,
  [DATABASE_NAME],
  [OBJECT_NAME],
  [STATEMENT],
  CLIENT_IP
FROM SYS.FN_GET_AUDIT_FILE('E:\Audit\*.sqlaudit', DEFAULT, DEFAULT)
WHERE ACTION_ID = 'SL'
